FROM mambaorg/micromamba:1.5.8
RUN micromamba install -y -n base \
    -c defaults -c bioconda -c conda-forge \
    -c r admixture 2>/dev/null || \
    micromamba install -y -n base \
    -c conda-forge plink2 && \
    micromamba clean --all --yes
