FROM python:3.10-slim-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc g++ cmake git \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir numpy scipy pandas
RUN pip install --no-cache-dir metacells
RUN pip install --no-cache-dir boto3 azure-storage-blob azure-identity

# OmniBioAI tool runtime
COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip install . --no-cache-dir

CMD ["python", "-m", "tools.generic_sif_runner.run"]
