# OmniBioAI — dgllife
# Purpose: Build the OmniBioAI container image for dgllife.
# Author: Manish Kumar <manish@omnibioai.org>
# Base image
FROM python:3.11-slim-bookworm

# Python dependencies
RUN pip install torch dgl dgllife --no-cache-dir

# Runtime dependencies
RUN pip install boto3 azure-storage-blob azure-identity --no-cache-dir

COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip install . --no-cache-dir

# Entrypoint and default command
CMD ["python", "-m", "tools.generic_sif_runner.run"]
