# OmniBioAI — macs2
# Purpose: Build the OmniBioAI container image for macs2.
# Author: Manish Kumar <manish@omnibioai.org>
# Base image
FROM python:3.11-slim-bookworm
# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake && rm -rf /var/lib/apt/lists/*
# Python dependencies
RUN pip install numpy cython --no-cache-dir
RUN pip install macs2 --no-cache-dir --no-binary=:all:

# Runtime dependencies
RUN pip install boto3 azure-storage-blob azure-identity --no-cache-dir

COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip install -e . --no-cache-dir

# Entrypoint and default command
CMD ["python", "-m", "tools.generic_sif_runner.run"]
