FROM python:3.10-slim-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc g++ cmake git \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir numpy scipy pandas
RUN pip install --no-cache-dir metacells
RUN pip install --no-cache-dir boto3 azure-storage-blob azure-identity
