FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
RUN pip install interpret --no-cache-dir

RUN pip install boto3 azure-storage-blob azure-identity --no-cache-dir

COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip install . --no-cache-dir

CMD ["python", "-m", "tools.generic_sif_runner.run"]
