# OmniBioAI — scrublet
# Purpose: Build the OmniBioAI container image for scrublet.
# Author: Manish Kumar <manish@omnibioai.org>
# Base image
FROM python:3.11-slim-bookworm
# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential && rm -rf /var/lib/apt/lists/*
# Python dependencies
RUN pip install annoy --no-cache-dir && \
    pip install scrublet --no-cache-dir
# Runtime dependencies
RUN pip install boto3 azure-storage-blob azure-identity --no-cache-dir
COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip install -e . --no-cache-dir
# Entrypoint and default command
CMD ["python", "-m", "tools.generic_sif_runner.run"]
